### ISSUE TITLE
Release a new version supporting Python 3

### ISSUE THREAD

**Issue by nth10sd** [sunpinyin/sunpinyin#107]
This will soon be removed [from Gentoo Linux](https://bugs.gentoo.org/695010), please [cut a new release](https://github.com/sunpinyin/sunpinyin/releases) supporting Python 3, which has already landed on master.

**Comment by XVilka** [comment]
Probably a duplicate of https://github.com/sunpinyin/sunpinyin/issues/94#issuecomment-781902193

**Comment by tchaikov** [comment]
@nth10sd sorry for the latency. just cut a new release, see https://github.com/sunpinyin/sunpinyin/releases/tag/v3.0.0-rc2
