### ISSUE TITLE
Add "None" option for Ch/En Switch Key

### ISSUE THREAD

**Issue by xiazeyu** [sunpinyin/sunpinyin#129]
For Chinese and English Dual Input System on iBus, I'm now using two input methods:
1. iBus's built-in English input method for English input.
2. Sunpinyin for Chinese input.

The aim is to let sunpinyin focus on Chinese input, and let iBus's built-in English input method handle the English input.
To achieve that, sunpinyin does not need to have any English input functionality.

I have use this solution for many years on Windows, but on Linux, Ch/En Switch Key can not be disabled, which means that I may frequently touch the *Ch/En Switch Key* by mistake, which is annoying.

**Comment by xiazeyu** [comment]
It seems some related code is at 
https://github.com/sunpinyin/sunpinyin/blob/master/wrapper/ibus/setup/setup.xml#L2121
https://github.com/sunpinyin/sunpinyin/blob/master/wrapper/ibus/po/ibus-sunpinyin.po#L128

**Comment by JohnYu98** [comment]
Commenting out the contents of the `SunPinyinEngine::update_mode_key` function in the `sunpinyin/warpper/ibus/src/sunpinyin_engine.cpp` file can disable the Ch/En Switch function.

disable Ch/En Switch: https://github.com/JohnYu98/sunpinyin/blob/patch-1/wrapper/ibus/src/sunpinyin_engine.cpp#L433

![en_ch_swithc](https://user-images.githubusercontent.com/43883192/140682600-8edcd80b-7fba-4cec-b6b1-b6b535c3b3ab.png)
