### ISSUE TITLE
How to use SunPinyin as a standalone XIM server?

### ISSUE THREAD

**Issue by NikitkoCent** [sunpinyin/sunpinyin#139]
Hey! I would like to look at how SunPinyin works as a XIM server but can't find any information about how to do it.
Could you help with that, please?

I tried to install the `xsunpinyin` package and set the following environment variables
```sh
QT_IM_MODULE=xim
GTK_IM_MODULE=xim
XMODIFIERS="@im=xsunpinyin"
```

But I don't understand which input source I should use to "trigger" the _xsunpinyin_. Ubuntu 20.04.4 LTS.

**Comment by mikeandmore** [comment]
Wow, I'm surprised that people are still using this!

You'll need to start xsunpinyin manually in `.xinitrc` or `autostart.sh`...

**Comment by NikitkoCent** [comment]
@mikeandmore, actually I just wanted to see how it works.

You're right, there should be the `xsunpinyin` daemon. (under Ubuntu you can switch to `xsunpinyin` IM via `gnome-language-selector`).

After that, the only thing I needed to do is just to press Ctrl+Shift+Space to activate the IM. It still works!

I think the issue can be closed, thanks!
