### ISSUE TITLE
github 版 的 sunpinyin 的拼音输入的一个问题.

### ISSUE THREAD

**Issue by zw963** [sunpinyin/sunpinyin#31]
新版本的 sunpinyin, 在输入  `省略` 的时候, 我(一般人都会吧) , 输入为 `shenglue`, 但是会输出
`生路恶`, 只有输入 `shenglve` 才有效. 

请问, 这是有意为之吗? 这给我造成了很大的困扰!! 其他输入法(包括早期版本都没有这个问题).

**Comment by kuchaguangjie** [comment]
这个 简单 又 严重的 bug 至今没有解决, 在最新的 mint 系统上 还是一样的问题, 搜遍了 google 没有一个清晰的解决方案, 只能说 这个项目不适合再使用了, 用 googlepinyin 就好了以后

**Comment by CasperVector** [comment]
这个 issue 里提到了若干个问题，你遇到的是哪个都不说清楚怎么能让别人帮你？

以及这些问题应该都可以通过把词库文件升级到正确版本来解决；我刚查看了一下 mint 和 ubuntu 的软件仓库，没有发现其中 sunpinyin 程序库和词库文件之间有明显的不兼容问题。因此很有可能是你自己机器上的软件源配置有问题；你机器上的 libsunpinyin3 和 sunpinyin-data 两个包是分别什么版本的？

**Comment by kuchaguangjie** [comment]
@CasperVector 我买了台新机器, 新装了 mint mate 17.2  (`Linux eric-pc 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`), 就发现 sunpinyin 中 xue 都变成了 xiong, 然后 google 上搜到的方案, 更新词库 做了 重启了还这样, 有人写了个 工具 Python 脚本 可是 需要连接 dropbox, 也连不上, 所以也用不了 ... 没办法了, 就装了 googlepinyin, 还凑合着用.

**Comment by CasperVector** [comment]
dropbox 在我们推荐的处理方式中应该是不需要的。如之前提到的，你报一下自己机器上的 `libsunpinyin3` 和 `sunpinyin-data` 分别是什么版本。

**Comment by CasperVector** [comment]
呃，根据 ubuntu 的[软件仓库信息](http://packages.ubuntu.com/search?keywords=sunpinyin&searchon=names&suite=all&section=all)，`trusty` 的 `sunpinyin-data` 落后于了 `libsunpinyin3` 的版本（参考 #42）。

因此，如果你用的 ubuntu 软件源是 `trusty` 的，请用版本号中后缀日期不早于 20130220 的 `sunpinyin-data` 包中的 `lm_sc.t3g` 和 `pydict_sc.bin` 覆盖机器上的版本，比如[这个](http://packages.ubuntu.com/utopic/sunpinyin-data)。

**Comment by CasperVector** [comment]
请参考：https://bugs.launchpad.net/ubuntu/+source/open-gram/+bug/1361764。

**Comment by kuchaguangjie** [comment]
@CasperVector 这解决方法太复杂了, 作为一款软件, 不应该折磨用户, 另外你给的链接 点进去 是无效的.

**Comment by CasperVector** [comment]
首先，这一点都不麻烦：在 http://packages.ubuntu.com/utopic/sunpinyin-data 下载适合你机器处理器架构（amd64 或 i386）的包，然后双击就能安装了。

其次，这几乎完全是 ubuntu 打包的问题（我贴链接时没注意中文句号的问题，已改）；我说“几乎”是因为我在做相关 commit 时没有通知下游，这一点是我无法否认的过错。

最后，我以为一个用户既然选择了 Linux，就不应该衣来伸手、饭来张口了呢。

**Comment by kuchaguangjie** [comment]
sunpinyin 在 preference 方面 做的相当不错, 不然我也不会来这回复 并 尝试着 找到解决方案, 你们对社区的贡献是 非常值得赞扬的.

但是呢, 之前 翻遍了 google, 直到你刚刚的最后一条回复, 我没找到一个是真正的解决方法, 有许多之前的回复也是误导. 作为 用户 他不像开发者 非常清楚 这可能是什么问题, 我应该 用新版本 还是 旧版本, 这是很困惑的, 当你提到用 `lm_sc.t3g 和 pydict_sc.bin 覆盖机器上的版本` 的时候, 就更困惑了, 用户很难理解为 只是安装某个 deb 包.

如果我没来这里描述问题, 恐怕永远也找不到 解决方案. 你也不知道 trusty 的包版本有问题.

我也用 ibus-anthy, 这个包从 很久之前到现在 就没出现过中文输入法之类的问题, 所以我个人认为 软件开发 不仅仅是写完代码就结束了, 包括 打包 / 升级 / 文档 等等问题, 其实都应该关心, 自己写了个软件, 但是因为打包问题 用户用不了, 我觉得开发者应该是很 失望的, 是很迫切要解决这种问题的.

我说这些绝对不是为了 指责, 而是 把我个人的看法说出来, 我也是个软件开发人员, 我觉得这样对 软件 / 用户 / 社区 都是有益的, 也希望你们以后不断开发出好的软件来.

**Comment by CasperVector** [comment]
你的想法本身很值得肯定，但我们在 bug tracker 上讨论的目的不只是“知其然”就完了，而是要“知其所以然”：升级那两个数据文件是解决问题的关键，因此我觉得把它提出来是有道理的；对于只求解决问题的一般用户而言，的确是只告诉他们手工安一个 deb 包就行了。

**Comment by wengxt** [comment]
你应该去给 ubuntu trusty 汇报 bug，trusty 既然还 LTS 应该还可以更新修复的，这是下游的问题不是上游的问题。anthy 最新的发布在 6 年前，数据格式估计早就稳定很久了，这么比是没啥意义的。

@CasperVector ˊ_>ˋ 当初你改 ve ue 没想到现在还在背锅吧。回头想想如果更改一下策略可能更能避免问题。E.G. open-gram 加入版本号，sunpinyin 编译时需要检测从而保证打包肯定正确。又或者open-gram 数据文件自身加入版本号 sunpinyin 打开时检测。

**Comment by CasperVector** [comment]
看上面那个 launchpad 的链接，今年 4 月就已经有人报 bug 了，然并卵 ╮(╯▽╰)╭
我的确是想过加版本号的问题，但要比较完整地避免版本错乱的话，数据文件加版本号之后 ABI 也得改，这个得慎重考虑啊……
