### ISSUE TITLE
ibus-sunpinyin not working correctly with sunpinyin-2.0.4, gnome-3.8.0

### ISSUE THREAD

**Issue by yangyingchao** [sunpinyin/sunpinyin#41]
Lots of python packages have been renamed in gnome-3.8, so wrapper/ibus/setup/main.py needs to be updated.

I made some changes, and I'd like to share it: https://gist.github.com/yangyingchao/7928574.

Hope someone can integrate it into mainline, and help the others.

Regards

**Comment by lidaobing** [comment]
this issue can be closed
