### ISSUE TITLE
[Regression Bisected] fails to convert ue and iong syllables and crashes

### ISSUE THREAD

**Issue by xlz** [sunpinyin/sunpinyin#42]
I updated on Debian from libsunpinyin3 2.0.3+git20120607-1 to 2.0.3+git20130507-1. (Also see Debian bug [#730821](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=730821))

xsunpinyin will not display any candidate choices for yue, jiong, qiong, and xiong.

xsunpinyin will provide candidates for jue, que, and xue with actual candidates of jiong, qiong, and xiong.

After inputting yue, jiong, qiong, or xiong, the cursor will move to the front. Moving left or right at the moment will crash xsunpinyin with segfault:

```
Program terminated with signal 11, Segmentation fault.
#0  CIMIClassicView::_moveLeftSyllable (this=this@entry=0xc6e610,
mask=@0x7ffff27e728c: 5,
    searchAgain=searchAgain@entry=true) at src/ime-core/imi_view_classic.cpp:583
```

Bisection shows regression introduced in 4f9745c0a9556f4673f4b973ec8145c53c351a1d.

@CasperVector

**Comment by terrencestark** [comment]
一些用户可能会在想简单解决问题的时候搜到此贴，可以移歩：[ubuntu forum:解决ibus sunpinyin输入yue问题](http://forum.ubuntu.org.cn/viewtopic.php?f=180&t=457956&sid=b0980e8a6d2dfd4f0c33c4b562b5cb95&start=15)。下载安装deb包即可。感谢项目开发者！
