### ISSUE TITLE
2.0.4 release?

### ISSUE THREAD

**Issue by cicku** [sunpinyin/sunpinyin#43]
Hi,

Is it possible for you to release 2.0.4?

Thanks.

**Comment by felixonmars** [comment]
Hi yongsun,

Please let me know what I can help for doing a release, thanks!

**Comment by tchaikov** [comment]
https://github.com/sunpinyin/sunpinyin/releases, so consider it done.

@felixonmars, thanks for your interests to work on sunpinyin. sorry for the latency =(

**Comment by felixonmars** [comment]
Thanks for the info. I have bumped the Arch package to 3.0.0rc1
