### ISSUE TITLE
sun-pinyin MacOS-2.0.4.1104 cannot input anything on OS X 10.10 beta

### ISSUE THREAD

**Issue by sunjw** [sunpinyin/sunpinyin#47]
What steps will reproduce the problem?
1. Install sun-pinyin on OS X 10.10 public beta
2. Select sun-pinyin
3. Input

What is the expected output? What do you see instead?
Input text

What version of the product are you using? On what operating system?
Nothing inputed on OS X 10.10 public beta

**Comment by tchaikov** [comment]
closing now, reopen this issue if you can reproduce it with the latest release at https://github.com/sunpinyin/sunpinyin/releases
