### ISSUE TITLE
Shuangpin key for "ve"?

### ISSUE THREAD

**Issue by cyrildtm** [sunpinyin/sunpinyin#48]
Type "JT" with MSPY2003 shuangpin schematic, expecting get "绝" but getting "囧". 

Typing "JS" gives nothing. 

I came from fcitx https://code.google.com/p/fcitx/issues/detail?id=718 and noticed a commit which could possibly fix this problem https://github.com/sunpinyin/sunpinyin/commit/33091baa5a21682d465dc65db7bcfcf7722c0254. Is it possible a future commit includes this commit?

**Comment by CasperVector** [comment]
Perhaps updating your data file will help? cf. #42.
(Very sorry for such a long delay...)
Fell free to reopen if the problem persists after data file update.
