### ISSUE TITLE
Mac OS binary version

### ISSUE THREAD

**Issue by wanglongqi** [sunpinyin/sunpinyin#60]
I do not know whether this project is under active maintenance. I do not have Xcode installed on my laptop, I wounder if it is possible to publish an official build of sunpinyin in Mac OS. The old builds in Google code cannot run correctly in new Mac OSX system.

Regards,

**Comment by railwaycat** [comment]
I don't think `macos` wrapper still under active developing...

**Comment by tchaikov** [comment]
@wanglongqi @railwaycat this project is not under active develop. but i just tagged v3.0.0-rc1 at https://github.com/sunpinyin/sunpinyin/releases/tag/v3.0.0-rc1 and uploaded a precompiled osx bundle for sunpinyin. maybe you can give it a shot.

**Comment by whyhowadmin** [comment]
@tchaikov Tested, it is working under Mac 10.9. At least able to type words without crash..

**Comment by wanglongqi** [comment]
@tchaikov  Thanks, I tested it under my Mac. It is working now!

**Comment by tchaikov** [comment]
@whyhowadmin @wanglongqi thanks guys, have a nice week-end!
