### ISSUE TITLE
Use the right floating point function variants

### ISSUE THREAD

**Issue by lichray** [sunpinyin/sunpinyin#62]
libstdc++ makes `<cmath>` and `<math.h>` to be the same, but with libc++, `<math.h>` does not pull in C++ floating point overloads (`log(float)`, for instance.  Here is the bug we found, along with my suggested fix (include the C++ header, and `using` declarations):

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209369

**Comment by tchaikov** [comment]
@lichray thanks for reporting this issue. #63 should address it.
