### ISSUE TITLE
How to build this package

### ISSUE THREAD

**Issue by yuhai1023** [sunpinyin/sunpinyin#67]
I want to compile this package and use it to build the fcitx-sunpinyin package which I have create an issue on https://github.com/fcitx/fcitx-sunpinyin/issues/10. 
But when I clone the source and didn't find a method to compile it. There is neither configure file nor Makefile to auto build.
Then I conclude maybe I should compile in an original way. But there aren't any file to indicate the way to build or I didn't have find it. 
I am here to ask a way to build it in my linux computer which I didn't have an package manager like yum or apt-get to auto install this lib.

**Comment by tchaikov** [comment]
we use scons to build sunpinyin.
