### ISSUE TITLE
sunpinyin gets wrong word order.

### ISSUE THREAD

**Issue by zhangn1985** [sunpinyin/sunpinyin#70]
OS: debian 8&9, ubuntu 16.10
Sunpinyin: OS provided, 3.0.0~git20160910-1
sunpinyin-data: OS provided, 0.1.22+20131212-2
input platform: ibus & fcitx

![img20170102202108](https://cloud.githubusercontent.com/assets/832666/21589111/5d66a3c4-d129-11e6-8b36-716bc0e545dc.jpg)

I find https://github.com/sunpinyin/open-gram has some update. should I update it? and how?

**Comment by CasperVector** [comment]
Please see:
* Issue #42 for related changes to data file semantics.
* [This announcement](https://groups.google.com/forum/#!topic/sunpinyin-developers/4voLmmEVC_c) for related changes to language model generation utilities.
* Commit 7435ccb6 for changes to URLs for data files.

**Comment by zhangn1985** [comment]
when I update data file from MacOS release, fcitx-sunpinyin get normal.

I think it need let package maintainer know this.

**Comment by CasperVector** [comment]
Many thanks for your confirmation...
