### ISSUE TITLE
SunPinyin-MacOS-3.0.0.git-2016-0708.zip 安装包无法使用

### ISSUE THREAD

**Issue by fenghaichun** [sunpinyin/sunpinyin#84]

**Comment by ozzie00** [comment]
whether this issue is solved now?

**Comment by XueWei** [comment]
@fenghaichun  @ozzie00  你们的mac什么版本的? 最新发布了mac 11.5+ 可以用的版本安装包.  https://github.com/sunpinyin/sunpinyin/releases/tag/v3.0.0-rc2
